name: 'StackQL Studio - Setup StackQL'
description: 'Sets up StackQL CLI in your GitHub Actions workflow.'
author: 'Yuncheng Yang, StackQL'


runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
