name: 'Setup StackQL'

on:
  push:
    branches:
    - main
    - 'develop-**'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  stackql-versions:
    name: 'Stackql Versions'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup stackql
      uses: ./
      with:
        authObjString: ${{ secrets.AUTH_OBJECT_STR }}


    - name: Validate Stackql Version
      run: |
        stackql --version