name: 'Setup Terraform'

on:
  push:
    branches:
    - main
    - 'develop-**'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  stackql-versions:
    name: 'Stackql Versions'
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup stackql
      uses: ./

    - name: Validate Stackql Version
      run: stackql --version