name: 'Setup Terraform'

on:
  push:
    branches:
    - main
    - 'develop-**'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  stackql-versions:
    name: 'Stackql Versions'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup stackql
      uses: ./

    - name: Validate Stackql Version
      run: |
        chmod +x $(which stackql)
        stackql --version